[package]
name = "gpu-tracing"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.97"
bytemuck = "1.23.0"
pollster = { version = "0.4.0", features = ["macro"] }
wgpu = "25.0.0"
winit = "0.29"
